In [9]:
pip install numpy

     ---------------------------------------- 14.6/14.6 MB 4.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [31]:
import numpy as np

In [32]:
a=np.array([1,2,3])

In [33]:
print(a)

[1 2 3]


In [34]:
sam=np.array([(3,4,5),(8,7,6)])

In [35]:
print(sam)

[[3 4 5]
 [8 7 6]]


In [36]:
sam2=np.transpose(sam)

In [37]:
print(sam2)

[[3 8]
 [4 7]
 [5 6]]


In [38]:
sam2.ravel()

array([3, 8, 4, 7, 5, 6])

In [39]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [47]:
sam2=np.zeros((3,2))

In [48]:
print(sam2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [50]:
np.random.random((5,5))

array([[0.07581734, 0.48635193, 0.42296623, 0.92245211, 0.75876796],
       [0.22292536, 0.28927483, 0.77074243, 0.44450781, 0.02303592],
       [0.19807756, 0.09039177, 0.28721427, 0.35192453, 0.46779678],
       [0.11720075, 0.92611989, 0.43822141, 0.98794908, 0.34329752],
       [0.37291257, 0.54502086, 0.6361302 , 0.66020011, 0.0408882 ]])